### PR TITLE
Translate templates_parser tests to e3.testsuite

### PR DESCRIPTION
**Pull request by VictorVerbeke**
Move tests from gnatpython to e3.testsuite.
Also fixed baselines that caused fails.

TN: V223-017

### CODE REVIEW

**Review by TurboGit — COMMENTED** [review]
How one is supposed to run the testsuite, I get an exception for all tests:

```
$ cd regtests
$ python3 ./testsuite.py tests/0002_testme/
_+Traceback (most recent call last):
_+  File "test.py", line 1, in <module>
_+    from test_support import *
_+  File "/home/obry/dev/repositories/git/template-parser/regtests/test_support.py", line 13, in <module>
_+    os.chdir(TESTDIR)
_+FileNotFoundError: [Errno 2] No such file or directory: ''
_
INFO     Summary:
_  FAIL         1

```

**Comment by VictorVerbeke** [comment]
Hello, 
Indeed this is tricky. I've used anod to test this ('anod test templates_parser' in a wave sandbox), but it requires to also edit the anod spec by removing gnatpython in the dependencies, and launching the test without "rlimit 1800" before the python call. I've set you as a reviewer on my anod change so you can cherry-pick the change and try with anod.

You could launch this by reproducing the anod testing behaviour (setting the correct env variables, calling the makefiles) but editing the spec and launching the test in a sandbox seems far less complicated. 

Regards,
Victor.

**Comment by TurboGit** [comment]
Victor, well I want to keep a way of testing as easy as possible for every one from the command line without requiring a sandbox. So I really need a way to run from a standard shell with a command line or script or whatever. Remember this is Open Source and it seems very important to have an as easy as possible way of testing.

**Review by TurboGit — APPROVED** [review]
Works for me now, thanks!

**Pull request merged**
